export { NotFoundPage } from './NotFoundPage';
export { MainPage } from './MainPage';
export { ProductPage } from './ProductPage';
export { RegistrationPage } from './RegistrationPage';
export { AuthPage } from './AuthPage';
export { UserPage } from './UserPage';
export { ProductEditPage } from './ProductEditPage';
export { ProductCreatePage } from './ProductCreatePage';
export { SearchResults } from './SearchResults';
